### ISSUE TITLE
Compote doesn't login to registry in Windows (PACMAN-929)

### ISSUE THREAD

**Issue by mateustoin** [espressif/idf-component-manager#66]
### The Component Manager version

v1.5.3

### ESP-IDF Version

v5.2

### python Version

3.11.2

### Operating System

Windows 11

### Description

I'm having trouble with the following command:
> compote registry login

When I try this command, this error appears:
> Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Scripts\compote.exe\__main__.py", line 7, in <module>
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\idf_component_manager\cli\core.py", line 74, in safe_cli
    cli()
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\idf_component_manager\cli\registry.py", line 101, in login
    auth_request = requests.Request('GET', auth_url, params=auth_params).prepare()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\requests\models.py", line 299, in prepare
    p.prepare(
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Espressif\python_env\idf5.2_py3.11_env\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'settings/tokens': No scheme supplied. Perhaps you meant https://settings/tokens?

I was just following the tutorial on the documentation. When I try the same thing on Linux, everything works perfectly.

### To Reproduce

```cpp
Just using the command ´compote registry login´
```

### Expected behaviour

I expected that the login page appears on the browser to complete the auth process.

### I have checked existing issues and online Documentation

- [X] I confirm I have checked existing issues and online Documentation.

**Comment by XDanielPaul** [comment]
Hi @mateustoin, I am sorry for the late response. I was able to reproduce the issue with the version 1.5.3, but managed to get it working with 2.0.0-dev1. Could you please check, if the login command works for you with the Component Manager version 2.0.0-dev1?
